"use client";

import { useEffect, useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { useParams } from "next/navigation";
import axios from "axios";
import Link from "next/link";

export default function ReportDetailPage() {
  const { token, API_URL } = useAuth();
  const { id } = useParams(); // fileId from URL
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // 🧠 Fetch insight from backend
  useEffect(() => {
    if (!id || !token) return;
    const fetchInsight = async () => {
      try {
        const res = await axios.get(`${API_URL}/ai/insight/${id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        setInsight(res.data);
      } catch (err) {
        console.error("❌ Failed to load insight:", err);
        setError("Failed to load report analysis.");
      } finally {
        setLoading(false);
      }
    };
    fetchInsight();
  }, [id, token]);

  if (loading)
    return (
      <div className="flex justify-center items-center min-h-screen text-gray-500">
        Loading report analysis...
      </div>
    );

  if (error)
    return (
      <div className="p-8 text-center text-red-600">
        <p>{error}</p>
        <Link href="/dashboard" className="text-indigo-600 underline">
          ← Back to Dashboard
        </Link>
      </div>
    );

  if (!insight)
    return (
      <div className="p-8 text-center">
        <p>No insight found for this report.</p>
        <Link href="/dashboard" className="text-indigo-600 underline">
          ← Back to Dashboard
        </Link>
      </div>
    );

  return (
    <main className="max-w-3xl mx-auto p-6 space-y-8 bg-white shadow rounded-lg">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900">
          Report Analysis
        </h1>
        <Link
          href="/dashboard"
          className="text-sm text-indigo-600 hover:underline"
        >
          ← Back
        </Link>
      </div>

      {/* --- Summary --- */}
      <section>
        <h2 className="text-xl font-semibold mb-2 text-gray-800">
          Summary (English)
        </h2>
        <p className="text-gray-700 whitespace-pre-line">
          {insight.summaryEnglish}
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2 text-gray-800">
          Summary (Roman Urdu)
        </h2>
        <p className="text-gray-700 whitespace-pre-line">
          {insight.summaryRomanUrdu}
        </p>
      </section>

      {/* --- Highlights --- */}
      {insight.highlights?.length > 0 && (
        <section>
          <h2 className="text-xl font-semibold mb-2 text-gray-800">
            Key Highlights
          </h2>
          <ul className="list-disc list-inside text-gray-700 space-y-1">
            {insight.highlights.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {/* --- Suggestions --- */}
      {insight.suggestions?.length > 0 && (
        <section>
          <h2 className="text-xl font-semibold mb-2 text-gray-800">
            Health Suggestions
          </h2>
          <ul className="list-disc list-inside text-gray-700 space-y-1">
            {insight.suggestions.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {/* --- Questions for Doctor --- */}
      {insight.questionsForDoctor?.length > 0 && (
        <section>
          <h2 className="text-xl font-semibold mb-2 text-gray-800">
            Questions for Your Doctor
          </h2>
          <ul className="list-decimal list-inside text-gray-700 space-y-1">
            {insight.questionsForDoctor.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>
      )}

      {/* --- Footer --- */}
      <footer className="pt-4 border-t text-sm text-gray-500 text-center">
        <p>
          AI analysis generated by <span className="font-medium">HealthMate</span>.
          Always consult your doctor for medical advice.
        </p>
      </footer>
    </main>
  );
}
